database_name: vanguard_ab
refresh_db: false
tables:
    clients:
        paths:
            - data/df_final_demo.txt

        separator: ","
        columns:
            client_id:
                original_name: client_id
                data_type: INTEGER
                primary_key: true
                pandas_dtype: int64

            client_since_year:
                original_name: clnt_tenure_yr
                data_type: FLOAT
                pandas_dtype: int64

            client_since_month:
                original_name: clnt_tenure_mnth
                data_type: FLOAT
                pandas_dtype: int64

            client_age:
                original_name: clnt_age
                data_type: FLOAT
                pandas_dtype: int64

            gender:
                original_name: gendr
                data_type: CHAR(1)
                pandas_dtype: category
                valid_categories: [U, M, F]
                fallback_category: 'U'

            number_of_accounts:
                original_name: num_accts
                data_type: FLOAT
                pandas_dtype: int64

            balance:
                original_name: bal
                data_type: FLOAT
                pandas_dtype: float64

            calls_6_months:
                original_name: calls_6_mnth
                data_type: FLOAT
                pandas_dtype: int64

            logons_6_month:
                original_name: logons_6_mnth
                data_type: FLOAT
                pandas_dtype: int64

    experiment:
        paths:
            - data/df_final_experiment_clients.txt

        columns:
            client_id:
                original_name: client_id
                data_type: INTEGER
                primary_key: true
                pandas_dtype: int64

            variation:
                original_name: Variation
                data_type: VARCHAR(20)
                pandas_dtype: category
                valid_categories: [Test, Control]

    visits:
        paths:
            - data/df_final_web_data_pt_1.txt
            - data/df_final_web_data_pt_2.txt

        columns:
            client_id:
                original_name: client_id
                data_type: INTEGER
                pandas_dtype: int64

            visitor_id:
                original_name: visitor_id
                data_type: VARCHAR(50)
                pandas_dtype: object

            visit_id:
                original_name: visit_id
                data_type: VARCHAR(50)
                pandas_dtype: object

            process_step:
                original_name: process_step
                data_type: VARCHAR(10)
                pandas_dtype: category
                valid_categories: [start, step_1, step_2, step_3, confirm]

            date_time:
                original_name: date_time
                data_type: DATETIME
                pandas_dtype: datetime64[ns]
