database_schema:
  tables:
    - table_name: clients
      columns:
        - column_name: client_id
          original_name: client_id
          data_type: INTEGER
          primary_key: true
          pandas_dtype: int64
        - column_name: clnt_tenure_yr
          original_name: clnt_tenure_yr
          data_type: FLOAT
          pandas_dtype: float64
        - column_name: clnt_tenure_mnth
          original_name: clnt_tenure_mnth
          data_type: FLOAT
          pandas_dtype: float64
        - column_name: clnt_age
          original_name: clnt_age
          data_type: FLOAT
          pandas_dtype: float64
        - column_name: gendr
          original_name: gendr
          data_type: CHAR(1)
          pandas_dtype: category
          valid_categories: [U, M, F]
        - column_name: num_accts
          original_name: num_accts
          data_type: FLOAT
          pandas_dtype: float64
        - column_name: bal
          original_name: bal
          data_type: FLOAT
          pandas_dtype: float64
        - column_name: calls_6_mnth
          original_name: calls_6_mnth
          data_type: FLOAT
          pandas_dtype: float64
        - column_name: logons_6_mnth
          original_name: logons_6_mnth
          data_type: FLOAT
          pandas_dtype: float64

    - table_name: client_variations
      columns:
        - column_name: client_id
          original_name: client_id
          data_type: INTEGER
          primary_key: true
          pandas_dtype: int64
        - column_name: Variation
          original_name: Variation
          data_type: VARCHAR(20)
          pandas_dtype: category
          valid_categories: [Test, Control]

    - table_name: client_visits
      columns:
        - column_name: client_id
          original_name: client_id
          data_type: INTEGER
          pandas_dtype: int64
        - column_name: visitor_id
          original_name: visitor_id
          data_type: VARCHAR(50)
          pandas_dtype: object
        - column_name: visit_id
          original_name: visit_id
          data_type: VARCHAR(50)
          pandas_dtype: object
        - column_name: process_step
          original_name: process_step
          data_type: VARCHAR(10)
          pandas_dtype: category
          valid_categories: [step_1, step_2, step_3, step_4]
        - column_name: date_time
          original_name: date_time
          data_type: DATETIME
          pandas_dtype: datetime64